Rising_Tide_project/Rising_Tide_App/urls.py
from django.urls import path, re_path
from . import views

app_name = 'Rising_Tide_App'
urlpatterns = [
    path('', views.home, name='home'),
    path('result', views.mapResult, name='mapResult'),
    path('resources', views.resources, name='resources'),
]

Rising_Tide_project/Rising_Tide_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

# set risiningtide/ as the base url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('risingtide/', include('Rising_Tide_App.urls')),
    path('', RedirectView.as_view(url = 'risingtide/', permanent = True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Rising_Tide_project/Rising_Tide_App/models.py
from django.db import models

# Model for the database latitude, longitude, and distance entries. Use latitude and longitude to get distance from coast
# The data for this database was drawn from the NASA Ocean Biology Processing Group's data set on coordinates to distance from coast
# It can be found here: https://oceancolor.gsfc.nasa.gov/docs/distfromcoast/
# However we loaded a reduced precision version into our database, only using a precision of .1 for latitude and longitude
class DistanceToCoast(models.Model):
    id = models.IntegerField(primary_key = True)
    longitude = models.FloatField(blank = True, null = True)
    latitude = models.FloatField(blank = True, null = True)
    distance = models.FloatField(blank = True, null = True)

    class Meta:
        managed = True
        db_table = 'distance_to_coast'

Rising_Tide_project/Rising_Tide_App/views.py
from django.http import Http404
from django.shortcuts import render
from Rising_Tide_App.models import DistanceToCoast
import math

# Create your views here.
def home(request):
    return render(request, 'Rising_Tide_App/home.html')

# fill and render the map result page
def mapResult(request):
    # a longitude, latitude, and elevation value are expected
    try:
        lng = float(request.GET['lng'])
        lat = float(request.GET['lat'])
        elevation = float(request.GET['elev'])
    except (NameError, TypeError):
        raise Http404("Invalid query parameters were passed")

    # the database only contains latitudes and longitudes ending with a decimal value of .1, .3, .5, .7, or .9
    # Thus round the lat and lng values to the nearest of these decimal points
    odd_rounded_lng = math.floor(5 * lng) * .2 + .1
    odd_rounded_lng = round(odd_rounded_lng, 1)
    odd_rounded_lat = math.floor(5 * lat) * .2 + .1
    odd_rounded_lat = round(odd_rounded_lat, 1)

    try:
        entry = DistanceToCoast.objects.get(longitude = odd_rounded_lng, latitude = odd_rounded_lat)
    except DistanceToCoast.DoesNotExist:
        raise Http404("An invalid longitude and latitude was passed.")

    chance = ""

    chances = ["very low", "low", "medium low", "medium", "medium high", "high", "extremely high"]

    # base chances on either being far enough from sea or elevation
    if (entry.distance > 100):
        chance = chances[0]
    elif (elevation < .5):
        chance = chances[6]
    elif (elevation < 1):
        chance = chances[5]
    elif (elevation < 1.5):
        chance = chances[4]
    elif (elevation < 2):
        chance = chances[3]
    elif (elevation < 2.5):
        chance = chances[2]
    elif (elevation < 10):
        chance = chances[1]
    else:
        chance = chances[0]

    lng = round(lng, 2)
    lat = round(lat, 2)
    elevation = round(elevation, 2)

    context = {
        'longitude': lng,
        'latitude': lat,
        'elevation': elevation,
        'chance': chance,
    }
    return render(request, 'Rising_Tide_App/mapResult.html', context)
    

def resources(request):
    return render(request, 'Rising_Tide_App/resources.html')

Rising_Tide_project/Rising_Tide_App/templates/Rising_Tide_App/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title> 
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <script src="{% static 'geolocate.js' %}"></script>
        <script src="{% static 'key.js' %}"></script>
    </head>

    <body class="containter" {% block loadFunc %}{% endblock %}>
        <div class="main-container d-flex w-100 p-3 mx-auto flex-column">
            <header class="mb-auto">
                <div>
                    <h3 class="float-md-start mb-0">Rising Tide</h3>
                    <nav class="nav nav-menu justify-content-center float-md-end">
                        <a class="nav-link" href="{% url 'Rising_Tide_App:home' %}">Home</a>
                        <a class="nav-link" href="{% url 'Rising_Tide_App:resources' %}">Resources</a>
                    </nav>
                </div>
            </header>
        </div>

        {% block contents %}
        {% endblock %}

    </body>
    
    
</html>

Rising_Tide_project/Rising_Tide_App/templates/Rising_Tide_App/home.html
{% extends "Rising_Tide_App/base.html" %}

{% block title %}
Rising Tide
{% endblock %}

{% block loadFunc %}
{% endblock %}

{% block contents %}
<div class="main-container mx-auto w-100 h-100 pb-5 row">
    <input
        id="search-input"
        class="controls"
        type="text"
        placeholder="Search Location"
    />

    <div class="col-12" id="map"></div>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=APIKEY&callback=initMap&libraries=places&v=weekly"
        async
    ></script>
</div>

{% endblock %}

Rising_Tide_project/Rising_Tide_App/templates/Rising_Tide_App/mapResult.html
{% extends "Rising_Tide_App/base.html" %} 

{% block title %}
Result
{% endblock %}

{% block loadFunc %}
onload="fillResultData()"
{% endblock %}

{% block contents %}
<div class="main-container mx-auto w-100 h-100 row">
    <div class="align-self-center">
        <h2 class="text-center">
            Rising Sea Levels
        </h2>
        <p class="text-center">
            At the coordinates you picked, at a longitude of {{ longitude }}, a latitude of {{ latitude }}, and an elevation of
            {{ elevation }} feet, there is a <span id="chance">{{ chance }}</span> chance that rising 
            sea levels will affect this spot. <span id="message"></span><br>
            The threat of rising sea levels is expected to affect hundreds of millions of people by the year 2100.
            If you want to learn more, check out our <a href="{% url 'Rising_Tide_App:resources' %}">resources page</a> with a few links about this topic.
        </p>
        <canvas id="water"></canvas>
    </div>
</div>

{% endblock %}

Rising_Tide_project/Rising_Tide_App/templates/Rising_Tide_App/resources.html
{% extends "Rising_Tide_App/base.html" %}

{% block title %}
Resources
{% endblock%}

{% block loadFunc %}
{% endblock %}

{% block contents %}


<div class="main-container mx-auto w-100 h-100 row " >
    <div class="align-self-center" >
        <p class="text-center">
            <h4>We're just computer science students so we're not the greatest sources on rising sea levels, but want to learn more? Here are some resources that can it explain it much better than we can.</h4>
            <ul>
                <li><a href="https://www.climate.gov/news-features/understanding-climate/climate-change-global-sea-level">NOAA</a> - A detailed article on why oceans are rising and how much they are rising by. </li>
                <li><a href="https://climate.nasa.gov/vital-signs/sea-level/">Nasa Ocean Level Rise Reporting</a> - Exact measurements on ocean level.</li>
                <li><a href="https://lao.ca.gov/Publications/Report/4121">CA Helping At Risk Communities </a> - Californian state legislative proposal on how to support those affected by rising sea levels.</li>
                <li><a href="https://www.climate.gov/news-features/climate-qa/what-can-we-do-slow-or-stop-global-warming">How to help reduce carbon emmissions</a> - Even though change will also require action on a legislative level here are a few ways you can help reduce your own carbon emissions.</li>
            </ul>
        </p>
        <canvas id="water"></canvas>
    </div>
    <script>
        drawWater(1);
    </script>
</div>

{% endblock %}